# for color
export CLICOLOR=1
# \h:\W \u\$
export PS1='\[\033[01;33m\]\u@\h\[\033[01;31m\] \W\$\[\033[00m\] '
export TERM=xterm-color

alias ll="ls -l"
export PATH="$HOME/bin:$PATH"
alias cgrep="grep --color --include=*.h --include=*.cpp --include=*.cc --include=*.c -r"
